[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  [functions.scheduled]
    [functions.scheduled.cron]
    function = "cron"
    schedule = "*/5 * * * *"
